### ISSUE TITLE
Error with pnpm

### ISSUE THREAD

**Issue by jbboehr** [azmenak/react-stripe-checkout#109]
```
Module not found: Error: Can't resolve 'prop-types' in 'node_modules/.registry.npmjs.org/react-stripe-checkout/2.6.3/node_modules/react-stripe-checkout/dist'
```

It appears that `react` and `prop-types ` are both run-time dependencies and not build-time dependencies.

**Comment by jbboehr** [comment]
This can be solved by simply adding `react` and `prop-types` to `dependencies`. My first inclination would be to set them to `*` so any other version constraints can set the actual version.

**Comment by jbboehr** [comment]
Based on [react-router](https://github.com/ReactTraining/react-router/blob/34412fdf07f116c1cce6db516b588b72771b1786/packages/react-router/package.json#L37-L46), perhaps the following would be best?

```json
  "dependencies": {
    "prop-types": "^15.5.8"
  },
  "peerDependencies": {
    "react": ">=15"
  }
```

**Comment by jaydenseric** [comment]
This isn't just an issue with pnpm, it is a broken package plain and simple.

It breaks tools like bundlephobia: https://bundlephobia.com/result?p=react-stripe-checkout

<img width="627" alt="screen shot 2018-10-16 at 12 42 42 pm" src="https://user-images.githubusercontent.com/1754873/46987696-06aed280-d141-11e8-931a-e7d1a6d3e579.png">
