### ISSUE TITLE
Passing Plan info to onToken?

### ISSUE THREAD

**Issue by homerlex** [azmenak/react-stripe-checkout#133]
I have a page that renders several buttons representing different Stripe product plans.  When onToken is invoked I need to know which button (which plan) was clicked on so I can send that info to our server.  Any thoughts on how this could be done?

**Comment by maartenpeels** [comment]
First: this is not a very clean/good solution and I think the best option is to implement Stripe yourself.

That said, you can wrap a `button` with `StripeCheckout`, on this button you can add an `onClick` that sets, for example, "selectedPlan" on the state. When the `onToken` get called you can get the "selectedPlan" from the state.

Example:

```
<StripeCheckout
  // All your props
>
  <button
    type="submit"
    className="btn btn-primary"
    onClick={() => this.setState({ selectedPlan: plan.id })}
  >
    Pay now
  </button>
</StripeCheckout>
```

**Comment by homerlex** [comment]
Yup - that was my exact workaround :-)

I've since changed it to select the plan via radio button.

We'll most likely implement our own UI eventually.  This is just to get things going.

Thanks a bunch.
