### ISSUE TITLE
Can we open the react stripe handler popup on click of another button.?

### ISSUE THREAD

**Issue by usamamashkoor** [azmenak/react-stripe-checkout#135]
Hi Can we open the react stripe handler popup on click of another button.?

For example if i click on the submit button if my form data is valid then i open the stripe handler and after the user fills out the stripe details in the popup then i send a request to my server.

Kindly help me on this...

Thanks in advance.

**Comment by koralarts** [comment]
I needed something similar in my project and here's what I did:

```
<StripeCheckout {...yourProps}>
   <button id="button-id">Invisible Trigger</button>
</StripeCheckout>

// Somewhere else in the code
onSubmit = () => {
   document.getElementById('button-id').click()
}
```

**Comment by usamamashkoor** [comment]
Thanks

**Comment by karafa00** [comment]
> Thanks

you gotta upvote the guy who answered your question

**Comment by usamamashkoor** [comment]
@koralarts in the react should not we update the dom in react way instead of manipulating it directly...?

**Comment by usamamashkoor** [comment]
> 
> 
> > Thanks
> 
> you gotta upvote the guy who answered your question

How can i upvote him..?

**Comment by koralarts** [comment]
> @koralarts in the react should not we update the dom in react way instead of manipulating it directly...?

Yes, but in my case, the trigger was coming from a Native bridge. An updated version of the could would look something like:

```
<StripeCheckout {...yourProps}>
   <button id="button-id" ref={elem => this.ref}>Invisible Trigger</button>
</StripeCheckout>

// Somewhere that has access to the ref
onSubmit = () => {
   this.ref.click()
}
```

**Comment by usamamashkoor** [comment]
Thanks for the help man.

**Comment by usamamashkoor** [comment]
Thanks for the help man.
