### ISSUE TITLE
Updated Stripe Checkout Library

### ISSUE THREAD

**Issue by siiiiilvio** [azmenak/react-stripe-checkout#137]
Hey! First of all thank you so much for this package, I've been using it in my apps and I love it.

Stripe has come out with a new Checkout library, do you plan on updating this package with it?

**Comment by Rmannn** [comment]
Any news on this ? This package will not be supported after september if not updated.

**Comment by taykcrane** [comment]
@Rmannn Where do you see that it won't be supported after September? This is news to me.

**Comment by KudMath** [comment]
@taykcrane https://stripe.com/docs/checkout#integration-custom
this library depends on :
```
This page is for the legacy version of Checkout

The legacy version of Checkout does not support the upcoming European Strong Customer Authentication requirements. European businesses using this integration after September 14, 2019 may experience an increased number of declines.

**Comment by taykcrane** [comment]
@KudMath Thank you. I spoke with Stripe. It's not being deprecated in September, just a warning for European businesses. They don't have a timeline on when they will be deprecating.

But would be nice for this library to still upgrade! It's very useful!

**Comment by rwieruch** [comment]
> We wanted to remind you about required changes to your Stripe integration. Upcoming industry-wide regulation will require Strong Customer Authentication (SCA) on many European payments starting 14 September. Unless you take action, payments that aren't authenticated may be declined by your customers' banks.

So I am not sure if customers just receive a mere warning ... I guess there will be declined payments for certain European banks.

**Comment by azmenak** [comment]
Currently, there are no plans to support the new version Stripe Checkout, IMO they really should have picked a different name because the new version is a completely different product.

The flow in the new version involves:
```
Click button → open checkout page in new tab → redirect to "success" page
                                             → or redirect "cancelled" page
```

If you need to support SCA, I'd suggest looking into Stripe Elements or switching to the new version without this library. Unfortunately there is no "upgrade" that will make this work without changes to your own code.

**Comment by rwieruch** [comment]
Thank you for stepping in @azmenak You are totally right about the naming, I was confused about the redirect as well. Thanks for clearing things up here and keep up the good work nonetheless! :)

**Comment by rwieruch** [comment]
I did the migration myself now. Using React + Express for server-side Stripe Checkout + Webhook Fulfillment. You can see a [minimal implementation over here](https://github.com/rwieruch/react-express-stripe ), for anyone who is interested in this.

<img width="1275" alt="Screenshot 2019-09-07 at 11 35 07" src="https://user-images.githubusercontent.com/2479967/64469431-3ead7280-d164-11e9-9960-68060e25ec9a.png">

Anyway, thanks @azmenak for your work on this library! Helped me a lot the last two years 👍

**Comment by wcandillon** [comment]
Makes sense @azmenak thank you for your great work!

**Comment by robinsingh-bw** [comment]
You dont need to upgrade but there is an additional step involved if you want to continue using this library as described here: https://stripe.com/docs/payments/payment-intents/migration#legacy-checkout

Need to handle the `requires_action` status on the new payment intent page. Any plans to support this?
