### ISSUE TITLE
Checkout Migration Guide

### ISSUE THREAD

**Issue by thisisusman** [azmenak/react-stripe-checkout#139]
Hi

Thanks for making this checkout easier in React Js. Was wondering if there is any release soon, which will cater the Checkout Migration Guide [https://stripe.com/docs/payments/checkout/migration#client-products](url) right now we are having a pop up which do all the payment. How can we migrate to the latest checkout page ?
![Untitled](https://user-images.githubusercontent.com/49227625/59243382-28f1e500-8c29-11e9-9731-9bd0f8ff723f.png)

**Comment by azmenak** [comment]
See my comments in #137
