### ISSUE TITLE
any plans for up and coming SCA?

### ISSUE THREAD

**Issue by jliebrand** [azmenak/react-stripe-checkout#140]
Just wondering if you are planning an update to support SCA?

https://stripe.com/docs/billing/migration/strong-customer-authentication#sca-migration-guide-for-billing

**Comment by juliengroch** [comment]
+1 I am interested. Guys how are you doing for SCA?

**Comment by KudMath** [comment]
same here

**Comment by rwieruch** [comment]
+ 1 :) https://github.com/azmenak/react-stripe-checkout/issues/137#issuecomment-524602834

**Comment by azmenak** [comment]
See https://github.com/azmenak/react-stripe-checkout/issues/137#issuecomment-524637739
