### ISSUE TITLE
autorun

### ISSUE THREAD

**Issue by thisKeeWord** [azmenak/react-stripe-checkout#17]
so i've created a form where all the input fields must be filled before the stripe button can trigger (to show the stripe checkout form). However, if any of the fields of the first form have or have not value, the stripe button still triggers on click immediately after showing the "this field must be filled" dialogue.

I've fixed this by adding two lines of code (which caters to my needs). Here's the resulting code:

```js
onClick: function() {
    _**if (this.props.info.pictureAmount && this.props.info.phone && this.props.info.topic) {**_
      if (ReactStripeCheckout.scriptDidError) {
        console.log('failed to load script');
      } else if (ReactStripeCheckout.stripeHandler) {
        this.showStripeDialog();
      } else {
        this.showLoadingDialog();
        this.hasPendingClick = true;
      }
    _**}**_
  },
```

**Comment by azmenak** [comment]
Hey @thisKeeWord, what you describe sounds right. If you need more control over the button, just passing in your own component would probably be best.

Eg. you could pass a "disabled" prop to your own button if the forms aren't filled.
```js
<StripeCheckout ...myProps>
  <button disabled={!(this.props.info.pictureAmount && this.props.info.phone && this.props.info.topic)}
</StripeCheckout>
```
