### ISSUE TITLE
LICENSE.md?

### ISSUE THREAD

**Issue by developerdizzle** [azmenak/react-stripe-checkout#18]
Would be great to have a license, perhaps MIT, so others can freely use/derive from this lib.

> Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work.

 https://help.github.com/articles/open-source-licensing/

**Comment by azmenak** [comment]
thanks @developerdizzle for pointing this out. Wasn't thinking of the licensing issues at all when I put this out.

I'll add an update as soon as I can with a LICENSE.md, for now you can assume MIT for this project.

**Comment by azmenak** [comment]
@developerdizzle added a license, hope that helps!

**Comment by developerdizzle** [comment]
You rock, thanks!
