### ISSUE TITLE
Invoke from code?

### ISSUE THREAD

**Issue by jasonswearingen** [azmenak/react-stripe-checkout#19]
I would like to automaticaly invoke the stripe-checkout via code  (not having the user click a button)   is this possible?  if so, please let me know what function to invoke.

For example, I know I can get a child component via the ```.refs[key]``` so I just need to know what function to invoke from that point.

Thank you.

**Comment by jasonswearingen** [comment]
I think i figured it out:
```
var stripeCheckout = this.refs["stripeCheckout"];
stripeCheckout.showStripeDialog();
```

but will leave this open so the maintainer can confirm!

**Comment by azmenak** [comment]
Yep, that should do it.

Might look at making this more "react-like" later, like adding a prop `dialogShown` defaulting to `false`, but that comes with its own set of API challenges...

**Comment by karltaylor** [comment]
Is this still the correct way of doing it? I can't seem to get it working
