### ISSUE TITLE
Incorrect amount in Stripe Checkout Dialog when multiple StripeCheckoutComponents

### ISSUE THREAD

**Issue by ekalvi** [azmenak/react-stripe-checkout#2]
Repro:
- include StripeCheckout component multiple times on a page with different amounts (amountA, amountB)
- click the 2nd checkout button (amountB)
- note the the incorrect amount (it uses the first amount...amountA)

See screens:
Note amount A:
<img width="427" alt="1-amounta" src="https://cloud.githubusercontent.com/assets/1478414/8833797/9eacc00e-307e-11e5-87fb-9f350c289867.png">
Click on amount B:
<img width="431" alt="2-amountb-before" src="https://cloud.githubusercontent.com/assets/1478414/8833799/9eb1dad0-307e-11e5-896b-5c81b5e17217.png">
See how Amount A is used:
<img width="438" alt="2-amountb-after" src="https://cloud.githubusercontent.com/assets/1478414/8833798/9eae0022-307e-11e5-9a59-cd9f650ed63e.png">

**Comment by Siyfion** [comment]
@azmenak Quick question; whilst I can see that this will now work from a UI perspective, I can't see how this works from a charging perspective. The amount sent to checkout is never passed on to the token handler, which you have defined as a global handler for all instances, so how do you access the specific instances `amount`?

**Comment by azmenak** [comment]
@Siyfion checkout is really only a front-end for creating stripe charge tokens. AFAIK, once you receive the token, you can do whatever you'd like, including charge a completely different amount then was displayed to the user (probably should avoid this though).

Presumably, you had to pass in the amount to checkout from _somewhere_, it seems that in your case you'll also have to pass that amount to your server along with the token.

Something along the lines of:
```js
function onStripeToken(token, email) {
  const params = {
    chargeToken: token,
    userEmail: email, // optionally can be received from checkout
    amount: getAmount() // some getter to grab the amount you passed
  };
  return axios.post('my-server-address').data(params);
}
```
