### ISSUE TITLE
xhrStripeTokenToMyServer is not defined

### ISSUE THREAD

**Issue by noabyuna** [azmenak/react-stripe-checkout#22]
It just be me but I keep getting this error when using the example code.

**Comment by shubsengupta** [comment]
I'm having the same issue.

**Comment by vysakh0** [comment]
@noabyuna That function is just an example. It means 'sending ajax (xhr) request to my server' it can be your `$.ajax` code. That's a sample handling once you get a `token`.

**Comment by noabyuna** [comment]
Ah i see.. Thanks for the reply :)

**Comment by noabyuna** [comment]
This can be closed
