### ISSUE TITLE
How to make email editable once passed as prop

### ISSUE THREAD

**Issue by vysakh0** [azmenak/react-stripe-checkout#23]
Probably a trivial question. 

```js

render: function() {
// ...
 <input type="text" 
 className="form-control" 
 placeholder="Enter your email"  
 onChange={this.setEmail}/>
      
<ReactStripeCheckout currency="GBP" 
amount={100}
token={this.pay} 
stripeKey="mykey" 
email={this.state.email} />
//...
}
```

This opens up a stripe modal window, and the email is set. But it's not editable. I was wondering if there was a way to edit the email once it's set in the stripe modal window?

**Comment by azmenak** [comment]
hey @vysakh0 seems like when the email is passed to `checkout.js` you can't make any edits. If you don't pass anything, the email field will be editable.
