### ISSUE TITLE
no shipping address in response

### ISSUE THREAD

**Issue by liesislukas** [azmenak/react-stripe-checkout#26]
It seems like a bug from Stripe side while using js api, but there is also seems to be a workaround, could you take a look?

http://engineering.koalasafe.com/how-to-capture-shipping-address-with-stripe-checkout/

**Comment by mikedizon** [comment]
Seems that it gets passed in as a separate parameter.

if your handler is currently written as onToken(token){}, modify it to onToken(token, address){}

The docs should be updated to include this

**Comment by mikedizon** [comment]
Per the docs:

> Note: Enabling either address option will give the user the ability to fill out both. Addresses are sent as a second parameter in the token callback.

**Comment by azmenak** [comment]
Hoping this has been resolved, everything seems to be working from my end.

**Comment by tfogg2** [comment]
[Send Shipping Info to Stripe with React-Stripe-Checkout](https://medium.com/@tfogg2/react-stripe-checkout-and-shipping-information-870f2d7d0705)
