### ISSUE TITLE
auto open with opened property

### ISSUE THREAD

**Issue by fourcolors** [azmenak/react-stripe-checkout#28]
Hi,

I have use case were I need to open the stripe form after the component mounts. It would be nice to pass in a property that does this for me vs my hacky way. 

Is there a current method to do this? I couldn't see one in the code.

**Comment by mikedizon** [comment]
could you share what hacky way you're using? i need this functionality as well

**Comment by JerryLeooo** [comment]
@fourcolors try passing the `closed` function?

**Comment by fourcolors** [comment]
so I passed in this but that didn't do anything closed={() => false

**Comment by mikedizon** [comment]
What about sticking a button in there and firing a click event when the component loads?

**Comment by azmenak** [comment]
Hi guys, I'm currently in the process of fixing up this component; unfortunately opening the checkout modal by passing in props (or some other programatic way) isn't possible as this would break on mobile and IE. 

This is a browser security issue, where browsers only allow popups to open from JS if the stack frame originates from an actual click event (calling `.onClick()` programmatically won't work either)

Also see: https://stripe.com/docs/checkout#integration-more-runloop

> ### How do I prevent the Checkout popup from being blocked?

> You need to call handler.open when the user clicks on an element on the page. Do not call handler.open in a callback. This design indicates to the browser that the user is explicitly requesting the popup. Otherwise, mobile devices and some versions of Internet Explorer will block the popup and prevent users from checking out. This only applies to custom integrations.

*Side note: Good feature to have too, can you image if any piece of JS on the internet could open new tabs whenever they wanted :P*

**Comment by azmenak** [comment]
I haven't done extensive testing, but I've added a new prop in version 2.0 `desktopShowModal`, based on #15 , with the caveat that **THIS WILL NOT WORK ON MOBILE**

**Comment by fourcolors** [comment]
man... I need this for mobile. Hum... Any ideas on why it won't work on mobile?

**Comment by azmenak** [comment]
Hi @fourcolors, this is a restriction in Safari for iOS. Stripe Checkout currently works on iOS by opening a new tab rather then overlaying an iFrame.

See my comment above:

> This is a browser security issue, where browsers only allow popups to open from JS if the stack frame originates from an actual click event (calling .onClick() programmatically won't work either)

**Comment by fourcolors** [comment]
Ah, ok so this is going to be iOS specific. That makes a more sense. My use case is I have an app web view that is using this page but for now, I'm only working in Android so I do see this being an issue util I'm rich enough to build an iOS app. 

Thanks for the PS!

**Comment by AndrewBragdon** [comment]
This is a bad experience anyway as a popup.  Can you just make an inline form instead of a popup?  Since when are popups a good UI?  That is why browsers block them!  Come on guys.

**Comment by jiteshkriplani** [comment]
Hi, anybody facing issue in IOS. For me its not working in IOS. Its not even opening in new tab however its opening in new tab in android devices.

**Comment by usamamashkoor** [comment]
Is their a way to run "handler.open" when we click on another button.

Mean is their a way we can open stripe checkout on another button click in react.js...?
