### ISSUE TITLE
Unexpected token `import`

### ISSUE THREAD

**Issue by samcorcos** [azmenak/react-stripe-checkout#34]
I just updated to 2.1.1 and I'm having a compilation issue. It seems to break on the ES2015 syntax within the compiled `dist/main.js` file.

```js
import React from 'react';
```

I downgraded back to 1.8 and it works fine. Thoughts?

**Comment by andrewhl** [comment]
+1

**Comment by azmenak** [comment]
Fixed in version 2.2.0 thanks for pointing this out!
