### ISSUE TITLE
"Type mismatch for option" warnings from Stripe

### ISSUE THREAD

**Issue by byte255** [azmenak/react-stripe-checkout#38]
`getConfig()` returned all possible configuration options even ones that were not defined as component's properties. As a result, Stripe displayed warnings in the console about config options being undefined instead of type string, boolean, etc.

This is how it looks like in Chrome console:

![image](https://cloud.githubusercontent.com/assets/6132086/17567289/12652d8c-5f82-11e6-96c8-24beeae67f6d.png)

Proposed PR #37 that fixes the issue.

**Comment by azmenak** [comment]
Fixed in version 2.2.2, thanks.
