### ISSUE TITLE
Babel compile issue

### ISSUE THREAD

**Issue by MZ2288** [azmenak/react-stripe-checkout#39]
Hi, 

When trying to compile the component using xcode I keep running into this issue with babel:

TransformError: /path/to/project/react-stripe-checkout/dist/main.js: Couldn't find preset 'es2015' relative to directory /path/to/project/node_modules/react-stripe-checkout

Your help would be appreciated!

**Comment by azmenak** [comment]
Not entirely sure how xcode comes into play here, but that error would happen if you're trying to rebuild the module but didn't run `npm install`

**Comment by azmenak** [comment]
Doesn't seem to be any issues here, closing.
