### ISSUE TITLE
ReferenceError: StripeCheckout is not defined

### ISSUE THREAD

**Issue by mbrochh** [azmenak/react-stripe-checkout#4]
The component seems to work fine, but for some reason that I just can't figure out, I always need to press button twice. The first time, it opens a new tab and shows an error message saying that there was an error and that I should try another browser if the problem persists. On subsequent clicks, it opens a new tab and correctly shows the stripe form.

**Comment by ayasin** [comment]
Just submitted a [pull request](https://github.com/azmenak/react-stripe-checkout/pull/5) to fix this issue.

**Comment by orhan-swe** [comment]
@ayasin The check is not working for me, I am not sure how StripeCheckout still can give this error after the check but it does. The problem originates from the fact that componentDidUpdate is calling updateStripeHandler before script has loaded. I have a pull request that fixes this. https://github.com/azmenak/react-stripe-checkout/pull/6

**Comment by azmenak** [comment]
Looks like #6 solves this, thanks everyone! Finally using this lib at my day job, so I'll be maintaining a lot more going forward :+1:
