### ISSUE TITLE
Missing class properties transform Error

### ISSUE THREAD

**Issue by BrianSHenderson** [azmenak/react-stripe-checkout#43]
I'm getting:

   While processing files with ecmascript (for target web.browser):
   credits/client/credits.js:34:2: /credits/client/credits.js: Missing class properties
   transform.

Line 34 is:
onToken = (token) => {

My Stripe Checkout line is:
                      <StripeCheckout
                        token={this.onToken}
                        stripeKey={Meteor.settings.public.stripepk}
                      />

I'm still fairly new to React so apologies if this is a very basic error.

Any ideas where I'm going wrong?

**Comment by Ransyn** [comment]
Hi Brian,

The error sounds like babel configuration and using unrecognised javascript language features, likely a transpiler or polyfill issue, and not an issue for this repo.  You're using es6 syntax, so it will not work in many browsers as-is.

Your line 34 example looks like where you would be defining the onToken method of your custom react component.  It's hard to say what might be causing your issue without seeing it in a broader context - eg the complete component definition and transpiler (eg babel) config - and how you're trying to run it, but you should start with looking at which (if any) babel plugins you have configured.

**Comment by BrianSHenderson** [comment]
Many thanks, I'm running through Meteor which might be causing the problems.  I'll take a look.

**Comment by azmenak** [comment]
This issue doesn't seem related to this library, so I'm closing for now.
