### ISSUE TITLE
Custom amount at checkout

### ISSUE THREAD

**Issue by shangsunset** [azmenak/react-stripe-checkout#44]
Is it possible to have customers choose a variable amount to pay rather than having a pay button that pays a certain amount?

Thanks.

**Comment by azmenak** [comment]
@shangsunset Stripe Checkout doesn't actually make any charges; once you have their card token you can make charges of any amount on your server.

**Comment by shangsunset** [comment]
I know Stripe Checkout doesn't charge, but is it possible to have multiple payment options/prices and let user to choose on the front end?

**Comment by ldco2016** [comment]
@azmenak 

Why was this closed? Was it ever resolved?

I believe @shangsunset  was looking for a dynamic amount? instead of having to add 5 dollars as he demonstrates above?
Or at least can the amount be remain blank I guess?

What about multiple payment options? All good questions.
