### ISSUE TITLE
Promise is not a constructor

### ISSUE THREAD

**Issue by rubenpa** [azmenak/react-stripe-checkout#45]
I am all of a sudden getting an error that says: `Promise is not a constructor`.  I had the code working before, but I'm not sure what I changed that broke it.  

Here is my component:

```
export default class CourseEnrollButton extends React.Component {
  constructor(props) {
    super(props);
    this.onToken = this.onToken.bind(this);
  }
  onToken(token) {
    console.log(token)
  }
  render() {
    const { collection } = this.props;
    const price = collection.price ? parseInt(collection.price / 100, 10) : 0;
    const key = Meteor.settings.public.STRIPE_PUBLISHABLE_KEY;
    const user = Meteor.user();
    let enrolled = false;
    if (user) {
      if (_.contains(user.isEnrolled)) {
        enrolled = true;
      }
    }
    if (enrolled) return <div></div>;
    return (
      <StripeCheckout
        name="My Site"
        description={collection.title}
        image={collection.cover}
        amount={collection.price}
        currency="USD"
        stripeKey={key}
        zipcode
        allowRememberMe
        token={this.onToken}
      >
        <div className="enroll-button">
          Enroll -&nbsp;
          <span className="enroll-cost">${price}</span>
        </div>
      </StripeCheckout>
    );
  }
}
```

The trace is:
```

TypeError: Promise is not a constructor
    at main.js:152
    at ReactStripeCheckout.componentDidMount (main.js:181)
    at ReactCompositeComponentWrapper.invokeComponentDidMountWithTimer (ReactCompositeComponent.js:60)
    at CallbackQueue.notifyAll (CallbackQueue.js:67)
    at ReactReconcileTransaction.close (ReactReconcileTransaction.js:81)
    at ReactReconcileTransaction.closeAll (Transaction.js:204)
    at ReactReconcileTransaction.perform (Transaction.js:151)
    at ReactUpdatesFlushTransaction.perform (Transaction.js:138)
    at ReactUpdatesFlushTransaction.perform (ReactUpdates.js:90)
    at Object.flushBatchedUpdates (ReactUpdates.js:173)
```

I am using Meteor if that makes a difference.  Any help or ideas would be much appreciated.  Thanks!

**Comment by azmenak** [comment]
This is strange, AFAIK `Promise` is in fact a constructor. Which browser are you running in?

**Comment by rubenpa** [comment]
I'm running in Chrome 52

**Comment by azmenak** [comment]
Not sure if this is related, but this line

```js
this.onToken = this.onToken.bind(this);
```

Isn't necessary unless you're using `this` within your `onToken()` function.

**Comment by azmenak** [comment]
Haven't been able to replicate this kind of issue, so I'm closing for now.

**Comment by rubenpa** [comment]
Ok.   I think it may be more of a Meteor issue. The older version works fine for now.  Thanks for a great library!

**Comment by sturoid** [comment]
Had the same issue with version 2.2.5. Had to to roll back to 1.8.0. Here is my checkout:

      <StripeCheckout
        name={product.name + ' - ' + product.description}
        amount={product.price}
        email={this.props.user.emails[0].address}
        triggerEvent='onTouchTap'
        token={this.purchaseWithCreditCard.bind(this, product, index)}
        stripeKey=STRIPE_PUBLISHABLE_KEY
      >
        <RaisedButton label='Buy with card' fullWidth={fullWidth} />
      </StripeCheckout>
