### ISSUE TITLE
Calling setState() from token callback?

### ISSUE THREAD

**Issue by oscar-b** [azmenak/react-stripe-checkout#51]
I'm getting the following React error when trying to call `this.setState()` from the token callback:

    Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ReactStripeCheckout component.

I don't understand why.. I'm trying to set a variable indicating that the payment request has been sent to the backend, in order to display a loading indicator. Is there a better way to do that?

**Comment by azmenak** [comment]
Sounds like there could be a scoping problem, make sure `this` in your token callback is bound to the react component you want to update.

**Comment by oscar-b** [comment]
@azmenak Yeah I thought so too but `onToken()` thinks `this` belongs to my component, not `ReactStripeCheckout`, at least as far as I can see. The strange thing is that the call succeeds and seems to work properly.

```javascript
class Finished extends React.Component {
	onToken = (token) => {
		console.log(this); // logs "Finished {}"
		this.setState({ paymentStarted: true }); // logs the error

		fetch(`https://...`, {
			method: 'POST',
			body: JSON.stringify(token),
		});
	}

	render() {
		return (<StripeCheckout token={this.onToken}>
			<Button big>
				<i className="fa fa-credit-card" aria-hidden="true" />Pay
			</Button>
		</StripeCheckout>);
    }
}
```
