### ISSUE TITLE
Retrieving Token ID in onToken section

### ISSUE THREAD

**Issue by BrianSHenderson** [azmenak/react-stripe-checkout#53]
The value isn't available to me, any ideas where I'm going wrong?

![screen shot 2016-09-22 at 10 21 36](https://cloud.githubusercontent.com/assets/2174330/18742895/7097091e-80ae-11e6-829d-bb5d0573ca47.png)

**Comment by azmenak** [comment]
Hi @BrianSHenderson, it looks like you're running the code in the sample section of the README; the native `fetch` function resolves a `Response` object. (See https://developer.mozilla.org/en-US/docs/Web/API/Response). You'll have to do something like call `.json()` on that object to get the value in the body.

Try running a `console.log()` before the fetch to see the data coming back from StripeCheckout.

**Comment by BrianSHenderson** [comment]
Thanks for the response, my fetch line says: fetch('/save-stripe-token' but I see no way of passing a destination of where to post the data to.  I seem to be reading the data from a blank page, how do I set this?

**Comment by azmenak** [comment]
That's just an example of passing the data in `token` to your own server at the endpoint `/save-stripe-token`. You'll have to change what is done with the token object based on how your sever is setup.
