### ISSUE TITLE
Passing metadata

### ISSUE THREAD

**Issue by XXChester** [azmenak/react-stripe-checkout#55]
Can you provide an example of how to pass metadata to stripe?

https://stripe.com/blog/adding-context-with-metadata

Thanks,

**Comment by azmenak** [comment]
Hi @XXChester, Stripe Checkout (as well as the underlying `stripe.js`) are only used for creating tokens to be used on server to create charges. You would need to add metadata on your own server.

**Comment by XXChester** [comment]
Sorry for the late response, I only got around to looking into this further and you are correct. Adding a metadata hash to the charge.create JSON did the trick.

Thanks
