### ISSUE TITLE
POST to load to new page after submission

### ISSUE THREAD

**Issue by danielhpatton** [azmenak/react-stripe-checkout#63]
Is it possible to POST the callback to a destination within the app after submission. Specifically, I want to send the user to a Thank You page after submission. 
<img width="355" alt="screen shot 2017-02-14 at 10 05 19 pm" src="https://cloud.githubusercontent.com/assets/3790590/22961245/d3b32da0-f301-11e6-89f6-b1145e167fb9.png">
<img width="401" alt="screen shot 2017-02-14 at 10 06 03 pm" src="https://cloud.githubusercontent.com/assets/3790590/22961246/d3b46ca6-f301-11e6-88c7-79b139b8a520.png">

**Comment by azmenak** [comment]
There are many different ways to do this, eg. Add token to form and submit, send to server and redirect, etc.

This is beyond the scope of this project.
