### ISSUE TITLE
What about cross-origin access?

### ISSUE THREAD

**Issue by heymartinadams** [azmenak/react-stripe-checkout#64]
Since my React code is hosted on a static hosting domain, and my PHP is hosted on a non-static hosting domain, I’m running into the CORS issue.

`Fetch API cannot load https://myapp.000webhostapp.com/charge.php. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by heymartinadams** [comment]
I was able to specify `header("Access-Control-Allow-Origin: *")` (temporarily—I know it’s not recommended) inside the `https://(myappname).000webhostapp.com/charge.php` file to allow for cross-origin resource sharing (CORS). However, `stripeToken` on the PHP side still doesn’t seem to be recognizing the token.

This is what I specified inside the React component:
```
fetch('https://(myappname).000webhostapp.com/charge.php', {
	method: 'POST',
	mode: 'cors',
	body: {
		stripeToken: token.id,
		stripeEmail: this.props.data.user.email
	}
})
```

Here’s my PHP code:
```
<?php
	header("Access-Control-Allow-Origin: *");
	require_once('../config.php');
	$token	= $_POST['stripeToken'];
	$email	= $_POST['stripeEmail'];
	$customer = \Stripe\Customer::create(array(
			'email' => $email,
			'source'	=> $token
	));
	$charge = \Stripe\Charge::create(array(
			'customer' => $customer->id,
			'amount'	 => 999,
			'currency' => 'usd',
			'description' => 'Life Purpose App',
			'source' => $token
	));
	echo '<h1>Successfully charged $9.99.</h1>';
?>
```

And, finally, the console.log:
![snippet](https://cloud.githubusercontent.com/assets/11673745/23010424/385cb842-f3d0-11e6-84ee-a9fd838a3984.png)

**Comment by heymartinadams** [comment]
... and if I try to `.json()` the `response`, I get an error: `SyntaxError: Unexpected token < in JSON at position 0`

**Comment by azmenak** [comment]
This is an issue with your server code.

**Comment by heymartinadams** [comment]
Thanks, @azmenak. In case of interest, I was able to figure out another way how to use `react-stripe-checkout`. https://medium.com/@ConsciousApps/integrating-stripe-with-react-graphql-and-apollo-client-e09fdc9e5b95#.38e8qlbdg
