### ISSUE TITLE
Stripe Elements?

### ISSUE THREAD

**Issue by irfaan** [azmenak/react-stripe-checkout#65]
Hi! Wonderful repo - thank you so much for creating it!

Is it fairly straightforward to do the same with Stripe's new Elements feature?
https://stripe.com/docs/elements/reference

Thanks again!
Irfaan

**Comment by azmenak** [comment]
Hi @irfaan appreciate it :)

I did not know Stripe created this until today!

I don't think adding Elements is in the scope of this project, but I'll talk to my other team members about using it our current project; we'll definitely be open-sourcing a react component for that if we do go ahead with it.
