### ISSUE TITLE
Do not call onClosed if component is not mounted

### ISSUE THREAD

**Issue by waynebrantley** [azmenak/react-stripe-checkout#71]
If the closing of the component changes state in such a way that the checkout component is not shown, you will get the error below.

```
Warning: setState(...): Can only update a mounted or mounting component. 
This usually means you called setState() on an unmounted component. 
This is a no-op. Please check the code for the ReactStripeCheckout component.

```

This is because the checkout.js calls the onClosed
```
	  if (this..isMounted)
		this.setState({ open: false });
```
and set isMounted = false in componentWillUnmount solves it.

@azmenak Is there any chance you can look at this and also the other open pull requests.  What you have done here is effect, just needs a few tweaks?

**Comment by wcandillon** [comment]
It would be great if this bug could be fixed.
