### ISSUE TITLE
Delete email from checkout window

### ISSUE THREAD

**Issue by julian91** [azmenak/react-stripe-checkout#82]
Hey,
I am not using the window to do payments, rather to add cards to an account and could not find a way to remove the email field.
I will attach the customers details to the stripe customer object on the backend, so the frontend email input is not required.

I've tried setting the email prop to null, undefined, false, empty string...nothing does the job.

Any help appreciated.
Julian

**Comment by azmenak** [comment]
This is a restriction from Stripe's end, if you already have the email you can pre-fill it with the `email` prop. AFAIK, there's nothing actually preventing you from adding the token received to any stripe customer.
