### ISSUE TITLE
Error: Cannot set property isMounted of #<ReactComponent> which has only a getter

### ISSUE THREAD

**Issue by SachaG** [azmenak/react-stripe-checkout#83]
I've been using version 2.4.0 of this package without any issues, but after upgrading to 2.6.1 I started getting this error:

```
Cannot set property isMounted of #<ReactComponent> which has only a getter
```

Which I assume comes from [this line](https://github.com/azmenak/react-stripe-checkout/blob/master/StripeCheckout.js#L200). I really don't know what it means though. Any ideas?

**Comment by pdeva** [comment]
i am getting this too since upgrading to 2.6.1

**Comment by michaellyons** [comment]
isMounted is a **React.Component** instance method which has been considered deprecated and its use discouraged for some time now: [React Article](https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html).

Simply renaming the instance variable is what allowed it to keep working for me so I created a pull request with that change.

**Comment by heymartinadams** [comment]
Until @azmenak approves the PR, I added this into the `package.json` prior to building:
```
"build-copy": "cp ./resources/build-prepare/react-stripe-checkout/dist/main.js ./node_modules/react-stripe-checkout/dist/main.js",
```
Which basically just copies [this file](https://github.com/michaellyons/react-stripe-checkout/blob/cb9bf3d3611b26ad53500a7496ede49df146c6a6/StripeCheckout.js) into the node modules.

**Comment by tvl83** [comment]
thank you @heymartinadams for this workaround! :D

**Comment by phanthinh** [comment]
It's still not working for me. Can you help me??

**Comment by Bastardly** [comment]
I got the same error on an old component, where 'this.isMounted' was defined. The solution wasn't ideal, but I renamed 'this.isMounted' to 'this.mounted' and it worked. (using React 16.8.1 )

**Comment by krnlde** [comment]
Two years later its probably best practice to use `AbortController` instead to cleanup pending XHR requests aswell.
