### ISSUE TITLE
How to create a source instead of token?

### ISSUE THREAD

**Issue by ChaituVR** [azmenak/react-stripe-checkout#88]
I am not sure if it makes sense, i am trying to play with 3D secure authentication and it need a source instead of token..

The documentation says

`you should create a Source instead of a Token by calling the createSource instead of the createToken method.`

how to achieve this with this module? (if this feature is available )

I found this example in vanilla Js but not really sure how to do it with this module / React
```
var handler = StripeCheckout.configure({
  key: stripePublishableKey,
  image: 'https://stripe.com/img/documentation/checkout/marketplace.png',
  locale: 'auto',
  allowRememberMe: false,
  token: function(token) {
    // use Checkout's card token to create a card source
    Stripe.source.create({
      type: 'card',
      token: token.id
    }, stripeCardResponseHandler);

    displayProcessing();
  }
});
```
Thanks :)

**Comment by azmenak** [comment]
This is a bit beyond the scope of docs for this project, Checkout can only create tokens, and a token must be created before creating a source regardless. 

You can use this component's `onToken` callback and call `Stripe.source.create(...)` in that handler, similar to what you have in that example.

**Comment by methyl** [comment]
@azmenak not sure if this is a recent Checkout.js update or it was like that before, but it seems it supports passing source callback instead of token if you are using custom integration (as react-stripe-checkout seem to do): https://stripe.com/docs/checkout#required 

![](http://i.imgur.com/Z1SkXzf.png)
