### ISSUE TITLE
the value   stripeKey={process.env.REACT_APP_STRIPE_KEY}  doesnt get replaced by the key provided. 

### ISSUE THREAD

**Issue by jpca999** [azmenak/react-stripe-checkout#91]
Heres my payments.js 

[import React, { Component } from 'react';
import StripeCheckout from 'react-stripe-checkout';
import { connect } from 'react-redux';
import * as actions from '../actions';

class Payments extends Component {
  render() {

    debugger;

    return (
      <StripeCheckout
        name="Emaily"
        description="$5 for 5 email credits"
        amount={500}
        token={token => console.log( ' 16- token   process.env.REACT_APP_STRIPE_KEY  =' , process.env.REACT_APP_STRIPE_KEY  )}
        stripeKey={process.env.REACT_APP_STRIPE_KEY}
      >
        <button className="btn">
          Add Credits
        </button>
      </StripeCheckout>
    );
  }
}

export default connect(null, actions)(Payments);
](url)

here is  .env.development 
REACT_APP_STRIPE_KEY=pk_test_U30-CHANGED-KEY-FCn,

![image](https://user-images.githubusercontent.com/1026325/33142947-2cd19974-cf86-11e7-81ea-73f41ded62fd.png)

![image](https://user-images.githubusercontent.com/1026325/33149142-98322254-cf9c-11e7-92d6-9be006a450bc.png)

**Comment by azmenak** [comment]
This isn't related to this project. I would start by checking your webpack config.
